apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: milestone-cert
spec:
  secretName: milestone-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - milestone.local
